import Footer from "@/components/Footer/Footer";
import Header from "@/components/Header/Header";
import { Fira_Code } from "next/font/google";
import "./globals.css";

const firaCode = Fira_Code({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={firaCode.className}>
        <div className="min-h-screen h-fit w-full content-container  z-auto  container mx-auto border-x border-p4">
          <div className="-z-30  animate-content animate-rotate"></div>

          {/* <div className="min-h-screen w-full border-x border-p4"> */}
          <Header />
          <div className="w-full">{children}</div>
          <Footer />
          {/* </div> */}
        </div>
      </body>
    </html>
  );
}
