import Footer from "@/components/Footer/Footer";
import Header from "@/components/Header/Header";
import { Fira_Code } from "next/font/google";
import "./globals.css";

const firaCode = Fira_Code({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={firaCode.className}>
        <div className=" min-h-screen p-1 content-container rounded-md z-auto  container mx-auto border-x border-p4">
          <div className="-z-30  animate-content animate-rotate"></div>

          {/* <div className="min-h-screen w-full border-x border-p4"> */}
          <Header />
          {children}
          <Footer />
          {/* </div> */}
        </div>
      </body>
    </html>
  );
}
