export const industries = [
  {
    name: "Sundarban Courier Service (Pvt.) Ltd.",
    link: "https://sundarban.com.bd/",
    role: "Frontend Developer",
    jobType: "Onsite",
    start: "2023-09-01",
    end: "Present",

    address: "Uttara, Dhaka-1230",
    duties: [
      "Develop responsive and visually engaging web interfaces using React and NextJs.",
      "Analyzing customer and party requirements, researching, and creating the best front-end solutions.",
      "Addressing real-world challenges with practical, efficient designs that improve user experience.",
      "Designing and implementing complex dashboards that are both functional and easy to use.",
      "Collaborating closely with back-end developers to ensure smooth integration between front-end and server-side components.",
    ],
    skills: [
      "TypeScript",
      "React",
      "Next.js",
      "Apollo",
      "GraphQL",
      "TailwindCSS",
      "MUI",
      "Shadcn UI",
      "Team Work",
    ],
  },
  {
    name: "Robato Systems (Pvt.) Ltd.",
    link: "https://robatosystems.com/",
    role: "MERN Stack Developer",
    jobType: "Remote",
    start: "2023-07-02",
    end: "2023-09-01",
    address: "Nodia, Uttar Pradesh, India",
    duties: [
      "Developed responsive and user-friendly interfaces for web applications.",
      "Developing server-side logic and APIs using  Express.js, and working with Mongoose.",
      "Integrating front-end and back-end components to create full-stack applications that meet project requirements.",
      "Working closely with senior developers, designers, and project managers to understand requirements and contribute to project development.",
    ],
    skills: [
      "JavaScript",
      "Next.js",
      "React",
      "TailwindCSS",
      "RESTful APIs",
      "JWT",
      "Express.js",
      "MongoDB",
      "MySQL",
    ],
  },
];
