export const industries = [
  {
    name: "Sundarban Courier Service (Pvt.) Ltd.",
    link: "https://sundarban.com.bd/",
    role: "Frontend Developer",
    jobType: "On-Site",
    duration: "Sep, 23 — Present",
    address: "Uttara, Dhaka-1230",
    duties: [
      "Develop responsive and visually engaging web interfaces using React and NextJs.",
      "Collaborated with back-end developers to integrate front-end and server-side components.",
      "Convert Figma, PSD to pixel perfect web pages.",
    ],
    skills: [
      "TailwindCSS",
      "TypeScript",
      "Next.js",
      "React",
      "MUI",
      "GraphQL",
      "Apollo",
    ],
  },
  {
    name: "Robato Systems (Pvt.) Ltd.",
    link: "https://robatosystems.com/",
    role: "MERN Stack Developer",
    jobType: "Remote",
    duration: "July, 23 — Sep, 23",
    address: "Nodia, Uttar Pradesh, India",
    duties: [
      "Building user interfaces and implementing designs using React, and Next.js.",
      "Developing server-side logic and APIs using  Express.js, and working with MongoDB.",
      "Integrating front-end and back-end components to create full-stack applications that meet project requirements.",
      "Working closely with senior developers, designers, and project managers to understand requirements and contribute to project development.",
    ],
    skills: [
      "TailwindCSS",
      "JavaScript",
      "Next.js",
      "React",
      "RESTful APIs",
      "JWT",
      "Express.js",
      "MongoDB",
      "MySQL",
    ],
  },
];
