export const projects = [
  {
    id: 1,
    name: "Dance School",
    title: "Summer Camp School",
    description:
      "Discover the artistry of dance at our vibrant dance school, offering a wide range of classes for all ages and skill levels. Experience the joy of movement and expression through our dance school's expert instruction, nurturing a passion for dance in a supportive and inclusive environment. Admin-email: admin@danceschool.com,. Password: Admin@626456",
    cover: "/images/dance-school/dance-school_banner.png",
    images: [
      "/images/dance-school/dance-school_banner.png",
      "/images/dance-school/dance-school_popularClass.png",
      "/images/dance-school/dance-school_popularInsturctor.png",
      "/images/dance-school/dance-school_signin.png",
      "/images/dance-school/dance-school_Dashboard.png",
      "/images/dance-school/dance-school_payment.png",
    ],
    technologies: [
      "HTML",
      "TailwindCSS",
      "React.js",
      "Axios",
      "TanStack Query",
      "JWT",
      "Firebase",
      "Stripe",
      "Express.js",
      "MongoDB",
    ],
    features: [
      "Admin, Instructor, User Dashboard",
      "Dynamic Popular Class and Instructor",
      "Authentication, JWT Implementation",
      "Payment Gateway by Stipe",
    ],
    liveLink: "https://dance-school-6fa61.web.app/",
    clientCode: "https://github.com/mahamudulhasan-me/dance-school",
  },
  {
    id: 2,
    name: "Toy Town",
    title: "Toy Product E-commerce",
    description:
      "A vibrant online destination that brings joy and excitement to all toy car enthusiasts, offering a wide range of high-quality and captivating toy cars for collectors and young adventurers alike.",
    cover: "/images/toyTown/toytown-banner.png",
    images: [
      "/images/toyTown/toytown-banner.png",
      "/images/toyTown/toy-town-sign-UP.png",
      "/images/toyTown/toy-town-add-Toy.png",
      "/images/toyTown/toy-town-blog.png",
      "/images/toyTown/toy-town-footer.png",
      "/images/toyTown/toy-town-my-Toy.png",
      "/images/toyTown/toy-town-shop-By-Category.png",
      "/images/toyTown/toy-town-all-Toys.png",
    ],
    technologies: [
      "HTML",
      "TailwindCSS",
      "JavaScript",
      "React.js",
      "Firebase",
      "Express.js",
      "MongoDB",
    ],
    features: [
      "Discover an Extensive Toy Collection",
      "Showcase Toy and CRUD Operation",
      "Secure Sign-In/Sign-Up Process",
    ],
    liveLink: "https://toy-town-82e43.web.app/",
    clientCode: "https://github.com/mahamudulhasan-me/toy-town.git",
  },
  {
    id: 3,
    name: "Cook and Yummy",
    title: "Chefs and Yummy Recipe",
    description:
      "An enticing culinary haven where food lovers can explore a world of delicious recipes, professional cooking tips, and mouthwatering inspiration, empowering everyone to unleash their inner chef and create delectable meals with confidence.",
    cover: "/images/cookAndYummy/cook-banner.png",
    images: [
      "/images/cookAndYummy/cook-banner.png",
      "/images/cookAndYummy/cook-signup.png",
      "/images/cookAndYummy/cook-best-chef.png",
      "/images/cookAndYummy/cook-best-recipe.png",
      "/images/cookAndYummy/cook-footer.png",
      "/images/cookAndYummy/details.png",
      "/images/cookAndYummy/recipi-details.png",
    ],
    technologies: [
      "HTML",
      "TailwindCSS",
      "JavaScript",
      "React.js",
      "Firebase",
      "Express.js",
      "MongoDB",
    ],
    features: [
      "A Handsome Home with Different Features",
      "Toy’s Showcase and CRUD Operation",
      "Authentication, JWT Implementation",
      "Secure Sign-In/Sign-Up Process",
    ],
    liveLink: "https://cook-and-yummy.web.app/",
    clientCode: "https://github.com/mahamudulhasan-me/cook-and-yammy.git",
  },
];
