export const projects = [
  {
    id: 5,
    isTranslate: true,
    name: "AutoCare",
    title: " Car Washing Services",
    description:
      "AutoCare is a user-friendly web application for booking car wash services online. Users can browse services, view details, and book appointments seamlessly, while administrators manage services, slots, and users through a dedicated dashboard. The platform is designed for efficiency, security, and a great user experience. Admin Credentials. E-mail: mahamudulhasan.org@gmail.com. Password: Mdun@626456. User Credentials. E-mail: mahmud@autocare.com. Password: User@626456",
    cover: "/images/autoCare/cover.jpeg",
    images: [
      "/images/autoCare/homePage.png",
      "/images/autoCare/loginPage.png",
      "/images/autoCare/team.png",
      "/images/autoCare/testimonial.png",
      "/images/autoCare/services.png",
      "/images/autoCare/serviceDetails.png",
      "/images/autoCare/footer.png",
      "/images/autoCare/checkout.png",
      "/images/autoCare/payment.png",
      "/images/autoCare/adminDashboard.png",
    ],
    technologies: [
      "TypeScript",
      "React",
      "Redux",
      "TailwindCSS",
      "Ant Design",
      "Framer Motion",
      "JWT",
      "REST API's",
      "Payment Gateway",
      "Express.js",
      "MongoDB",
    ],
    features: [
      "Service Booking: Easy-to-use interface for selecting and booking car wash services.",
      "User Authentication: Secure login, signup, and role-based access.",
      "Admin Dashboard: Manage services, slots, and users effectively.",
      "Payment Integration: Process payments securely using Aamarpay.",
      "Responsive Design: Optimized for desktop and mobile devices.",
      "Dynamic Reviews: Users can rate and review services with real-time updates.",
    ],
    liveLink: "https://autocare-client.vercel.app/",
    clientCode: "https://github.com/mahamudulhasan-me/autocare-client",
    serverCde: "https://github.com/mahamudulhasan-me/car-washing-system",
  },
  {
    id: 4,
    isTranslate: false,
    name: "Travel Tales",
    title: "Travel Tips & Destination Guides",
    description:
      "Travel Tales is a platform for travelers to share their stories, connect with others, and discover exciting travel tips and guides. With user-friendly features like secure login, personalized profiles, premium content, and admin controls, it creates a vibrant community for travel enthusiasts. Admin-email: mahmud@traveltales.com,. Password: Mdun@626456",
    cover: "/images/travel-tales/homePage-1.png",
    images: [
      "/images/travel-tales/loginPage.png",
      "/images/travel-tales/homePage-1.png",
      "/images/travel-tales/homePage-2.png",
      "/images/travel-tales/post.png",
      "/images/travel-tales/profile.png",
      "/images/travel-tales/payment.png",
      "/images/travel-tales/payment complete.png",
      "/images/travel-tales/dashboard.png",
    ],
    technologies: [
      "TypeScript",
      "Next.js",
      "TailwindCSS",
      "Shadcn/ui",
      "Framer Motion",
      "Recharts",
      "Axios",
      "JWT",
      "TanStack Query",
      "REST API's",
      "AamarPay",
      "Express.js",
      "MongoDB",
    ],
    features: [
      "User Registration & Login: Secure user login and registration via JWT.",
      "Personalized Profiles: Share stories, update profiles and connect with others.",
      "Rich Text Editor: Create detailed travel guides with formatting and media attachments.",
      "Upvotes & Comments: Discover popular posts and engage with the community through votes and comments.",
      "Premium Content: Verified users can access exclusive travel guides and tips.",
      "Payment Integration: Pay for premium content and verification using Aamarpay",
      "Dynamic News Feed: Infinite scrolling, upvotes, and sorting to highlight the best content.",
      "Admin Dashboard: Manage all users, view payment and post statistics, and handle user accounts and posts effectively.",
    ],
    liveLink: "https://travel-tales-client.vercel.app/",
    clientCode: "https://github.com/mahamudulhasan-me/travel-tales",
  },
  {
    id: 1,
    isTranslate: true,
    name: "Dance School",
    title: "Summer Camp School",
    description:
      "Discover the artistry of dance at our vibrant dance school, offering a wide range of classes for all ages and skill levels. Experience the joy of movement and expression through our dance school's expert instruction, nurturing a passion for dance in a supportive and inclusive environment. Admin-email: admin@danceschool.com,. Password: Admin@626456",
    cover: "/images/dance-school/cover.jpeg",
    images: [
      "/images/dance-school/dance-school_banner.png",
      "/images/dance-school/dance-school_popularClass.png",
      "/images/dance-school/dance-school_popularInsturctor.png",
      "/images/dance-school/dance-school_signin.png",
      "/images/dance-school/dance-school_Dashboard.png",
      "/images/dance-school/dance-school_payment.png",
    ],
    technologies: [
      "HTML",
      "TailwindCSS",
      "React.js",
      "Axios",
      "TanStack Query",
      "JWT",
      "Firebase",
      "Stripe",
      "Express.js",
      "MongoDB",
    ],
    features: [
      "Admin, Instructor, User Dashboard",
      "Dynamic Popular Class and Instructor",
      "Authentication, JWT Implementation",
      "Payment Gateway by Stipe",
    ],
    liveLink: "https://dance-school-6fa61.web.app/",
    clientCode: "https://github.com/mahamudulhasan-me/dance-school",
  },
  // {
  //   id: 2,
  //   isTranslate: true,
  //   name: "Toy Town",
  //   title: "Toy Product E-commerce",
  //   description:
  //     "A vibrant online destination that brings joy and excitement to all toy car enthusiasts, offering a wide range of high-quality and captivating toy cars for collectors and young adventurers alike.",
  //   cover: "/images/toyTown/toytown-banner.png",
  //   images: [
  //     "/images/toyTown/toytown-banner.png",
  //     "/images/toyTown/toy-town-sign-UP.png",
  //     "/images/toyTown/toy-town-add-Toy.png",
  //     "/images/toyTown/toy-town-blog.png",
  //     "/images/toyTown/toy-town-footer.png",
  //     "/images/toyTown/toy-town-my-Toy.png",
  //     "/images/toyTown/toy-town-shop-By-Category.png",
  //     "/images/toyTown/toy-town-all-Toys.png",
  //   ],
  //   technologies: [
  //     "HTML",
  //     "TailwindCSS",
  //     "JavaScript",
  //     "React.js",
  //     "Firebase",
  //     "Express.js",
  //     "MongoDB",
  //   ],
  //   features: [
  //     "Discover an Extensive Toy Collection",
  //     "Showcase Toy and CRUD Operation",
  //     "Secure Sign-In/Sign-Up Process",
  //   ],
  //   liveLink: "https://toy-town-82e43.web.app/",
  //   clientCode: "https://github.com/mahamudulhasan-me/toy-town.git",
  // },
];
