export const projects = [
  {
    id: 4,
    name: "Travel Tales",
    title: "Travel Tips & Destination Guides",
    description:
      "Welcome to Travel Tales, a dynamic platform designed for travel enthusiasts to share their stories, exchange valuable tips, and connect with fellow travelers! 🌍✈️ With user authentication, social features, and premium content access, this app offers a vibrant community experience where travelers can discover and contribute travel guides, tips, and experiences. Whether you're looking for your next adventure or sharing your latest one, Travel Tales has you covered. Admin-email: mahmud@traveltales.com,. Password: Mdun@626456",
    cover: "/images/travel-tales/homePage-1.png",
    images: [
      "/images/travel-tales/loginPage.png",
      "/images/travel-tales/homePage-1.png",
      "/images/travel-tales/homePage-2.png",
      "/images/travel-tales/post.png",
      "/images/travel-tales/profile.png",
      "/images/travel-tales/payment.png",
      "/images/travel-tales/payment complete.png",
      "/images/travel-tales/dashboard.png",
    ],
    technologies: [
      "TypeScript",
      "Next.js",
      "TailwindCSS",
      "Shadcn/ui",
      "Framer Motion",
      "Recharts",
      "Axios",
      "JWT",
      "TanStack Query",
      "REST API's",
      "AamarPay",
      "Express.js",
      "MongoDB",
    ],
    features: [
      "User Registration & Authentication: Secure user login and registration via JWT.",
      "Personalized Profiles: Share stories, update profiles, and connect with others.",
      "Rich Text Editor: Create detailed travel guides with formatting and media attachments.",
      "Upvotes & Comments: Discover popular posts and engage with the community through votes and comments.",
      "Premium Content: Verified users can access exclusive travel guides and tips.",
      "Payment Integration: Pay for premium content and verification using Stripe or Aamarpay.",
      "Dynamic News Feed: Infinite scrolling, upvotes, and sorting to highlight the best content.",
    ],
    liveLink: "https://travel-tales-client.vercel.app/",
    clientCode: "https://github.com/mahamudulhasan-me/travel-tales",
  },
  {
    id: 1,
    name: "Dance School",
    title: "Summer Camp School",
    description:
      "Discover the artistry of dance at our vibrant dance school, offering a wide range of classes for all ages and skill levels. Experience the joy of movement and expression through our dance school's expert instruction, nurturing a passion for dance in a supportive and inclusive environment. Admin-email: admin@danceschool.com,. Password: Admin@626456",
    cover: "/images/dance-school/dance-school_banner.png",
    images: [
      "/images/dance-school/dance-school_banner.png",
      "/images/dance-school/dance-school_popularClass.png",
      "/images/dance-school/dance-school_popularInsturctor.png",
      "/images/dance-school/dance-school_signin.png",
      "/images/dance-school/dance-school_Dashboard.png",
      "/images/dance-school/dance-school_payment.png",
    ],
    technologies: [
      "HTML",
      "TailwindCSS",
      "React.js",
      "Axios",
      "TanStack Query",
      "JWT",
      "Firebase",
      "Stripe",
      "Express.js",
      "MongoDB",
    ],
    features: [
      "Admin, Instructor, User Dashboard",
      "Dynamic Popular Class and Instructor",
      "Authentication, JWT Implementation",
      "Payment Gateway by Stipe",
    ],
    liveLink: "https://dance-school-6fa61.web.app/",
    clientCode: "https://github.com/mahamudulhasan-me/dance-school",
  },
  {
    id: 2,
    name: "Toy Town",
    title: "Toy Product E-commerce",
    description:
      "A vibrant online destination that brings joy and excitement to all toy car enthusiasts, offering a wide range of high-quality and captivating toy cars for collectors and young adventurers alike.",
    cover: "/images/toyTown/toytown-banner.png",
    images: [
      "/images/toyTown/toytown-banner.png",
      "/images/toyTown/toy-town-sign-UP.png",
      "/images/toyTown/toy-town-add-Toy.png",
      "/images/toyTown/toy-town-blog.png",
      "/images/toyTown/toy-town-footer.png",
      "/images/toyTown/toy-town-my-Toy.png",
      "/images/toyTown/toy-town-shop-By-Category.png",
      "/images/toyTown/toy-town-all-Toys.png",
    ],
    technologies: [
      "HTML",
      "TailwindCSS",
      "JavaScript",
      "React.js",
      "Firebase",
      "Express.js",
      "MongoDB",
    ],
    features: [
      "Discover an Extensive Toy Collection",
      "Showcase Toy and CRUD Operation",
      "Secure Sign-In/Sign-Up Process",
    ],
    liveLink: "https://toy-town-82e43.web.app/",
    clientCode: "https://github.com/mahamudulhasan-me/toy-town.git",
  },
  {
    id: 3,
    name: "Cook and Yummy",
    title: "Chefs and Yummy Recipe",
    description:
      "An enticing culinary haven where food lovers can explore a world of delicious recipes, professional cooking tips, and mouthwatering inspiration, empowering everyone to unleash their inner chef and create delectable meals with confidence.",
    cover: "/images/cookAndYummy/cook-banner.png",
    images: [
      "/images/cookAndYummy/cook-banner.png",
      "/images/cookAndYummy/cook-signup.png",
      "/images/cookAndYummy/cook-best-chef.png",
      "/images/cookAndYummy/cook-best-recipe.png",
      "/images/cookAndYummy/cook-footer.png",
      "/images/cookAndYummy/details.png",
      "/images/cookAndYummy/recipi-details.png",
    ],
    technologies: [
      "HTML",
      "TailwindCSS",
      "JavaScript",
      "React.js",
      "Firebase",
      "Express.js",
      "MongoDB",
    ],
    features: [
      "A Handsome Home with Different Features",
      "Toy’s Showcase and CRUD Operation",
      "Authentication, JWT Implementation",
      "Secure Sign-In/Sign-Up Process",
    ],
    liveLink: "https://cook-and-yummy.web.app/",
    clientCode: "https://github.com/mahamudulhasan-me/cook-and-yammy.git",
  },
];
